// <auto-generated />
namespace FC.PGDAL.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class MaterializedNews : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(MaterializedNews));
        
        string IMigrationMetadata.Id
        {
            get { return "201612311128124_MaterializedNews"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
