// <auto-generated />
namespace FC.PGDAL.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class SocialProfile2All_SocialProfile : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(SocialProfile2All_SocialProfile));
        
        string IMigrationMetadata.Id
        {
            get { return "201701141350098_SocialProfile2All_SocialProfile"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
