// <auto-generated />
namespace FC.PGDAL.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Update201701141524 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Update201701141524));
        
        string IMigrationMetadata.Id
        {
            get { return "201701141424134_Update201701141524"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
