namespace FC.MSDAL.Migrations
{
    using System;
    using System.Data.Entity.Migrations;
    
    public partial class refactor : DbMigration
    {
        public override void Up()
        {
            DropIndex("dbo.Advertisements", new[] { "Expires" });
            DropIndex("dbo.Advertisements", new[] { "PublishDate" });
            AddColumn("dbo.SocialProfileTypes", "ModifiedDate", c => c.DateTime(precision: 7, storeType: "datetime2"));
            AddColumn("dbo.SocialProfileTypes", "IsPublished", c => c.Boolean(nullable: false));
            AddColumn("dbo.SocialProfileTypes", "SortOrder", c => c.Int(nullable: false));
            AddColumn("dbo.SocialProfileTypes", "URL", c => c.String());
            AddColumn("dbo.SocialProfileTypes", "ArchiveDate", c => c.DateTime(precision: 7, storeType: "datetime2"));
            AddColumn("dbo.SocialProfileTypes", "CreatedDate", c => c.DateTime(precision: 7, storeType: "datetime2"));
            AddColumn("dbo.SocialProfileTypes", "DeleteDate", c => c.DateTime(precision: 7, storeType: "datetime2"));
            AddColumn("dbo.SocialProfileTypes", "AuthorID", c => c.Guid());
            AddColumn("dbo.SocialProfileTypes", "Deleted", c => c.Boolean(nullable: false));
            AddColumn("dbo.SocialProfileTypes", "IsDeleted", c => c.Boolean(nullable: false));
            AddColumn("dbo.SocialProfileTypes", "IsActive", c => c.Boolean(nullable: false));
            AddColumn("dbo.ResellerTypes", "ModifiedDate", c => c.DateTime(precision: 7, storeType: "datetime2"));
            AddColumn("dbo.ResellerTypes", "IsPublished", c => c.Boolean(nullable: false));
            AddColumn("dbo.ResellerTypes", "SortOrder", c => c.Int(nullable: false));
            AddColumn("dbo.ResellerTypes", "URL", c => c.String());
            AddColumn("dbo.ResellerTypes", "CreatedDate", c => c.DateTime(precision: 7, storeType: "datetime2"));
            AddColumn("dbo.ResellerTypes", "DeleteDate", c => c.DateTime(precision: 7, storeType: "datetime2"));
            AddColumn("dbo.ResellerTypes", "Deleted", c => c.Boolean(nullable: false));
            AddColumn("dbo.ResellerTypes", "IsActive", c => c.Boolean(nullable: false));
            AddColumn("dbo.ResellerGenres", "ModifiedDate", c => c.DateTime(precision: 7, storeType: "datetime2"));
            AddColumn("dbo.ResellerGenres", "IsPublished", c => c.Boolean(nullable: false));
            AddColumn("dbo.ResellerGenres", "SortOrder", c => c.Int(nullable: false));
            AddColumn("dbo.ResellerGenres", "URL", c => c.String());
            AddColumn("dbo.ResellerGenres", "CreatedDate", c => c.DateTime(precision: 7, storeType: "datetime2"));
            AddColumn("dbo.ResellerGenres", "DeleteDate", c => c.DateTime(precision: 7, storeType: "datetime2"));
            AddColumn("dbo.ResellerGenres", "Deleted", c => c.Boolean(nullable: false));
            AddColumn("dbo.ResellerGenres", "IsActive", c => c.Boolean(nullable: false));
            AddColumn("dbo.ResellerGenres", "Name", c => c.String());
            AddColumn("dbo.CalendarCardAds", "ModifiedDate", c => c.DateTime(precision: 7, storeType: "datetime2"));
            AddColumn("dbo.CalendarCardAds", "IsPublished", c => c.Boolean(nullable: false));
            AddColumn("dbo.CalendarCardAds", "SortOrder", c => c.Int(nullable: false));
            AddColumn("dbo.CalendarCardAds", "URL", c => c.String());
            AddColumn("dbo.CalendarCardAds", "CreatedDate", c => c.DateTime(precision: 7, storeType: "datetime2"));
            AddColumn("dbo.CalendarCardAds", "DeleteDate", c => c.DateTime(precision: 7, storeType: "datetime2"));
            AddColumn("dbo.CalendarCardAds", "Deleted", c => c.Boolean(nullable: false));
            AddColumn("dbo.CalendarCardAds", "IsActive", c => c.Boolean(nullable: false));
            AddColumn("dbo.CalendarCardAds", "Name", c => c.String());
            AddColumn("dbo.UNews", "Name", c => c.String());
            AddColumn("dbo.Plugins", "ModifiedDate", c => c.DateTime(precision: 7, storeType: "datetime2"));
            AddColumn("dbo.Plugins", "IsPublished", c => c.Boolean(nullable: false));
            AddColumn("dbo.Plugins", "SortOrder", c => c.Int(nullable: false));
            AddColumn("dbo.Plugins", "URL", c => c.String());
            AddColumn("dbo.Plugins", "CreatedDate", c => c.DateTime(precision: 7, storeType: "datetime2"));
            AddColumn("dbo.Plugins", "DeleteDate", c => c.DateTime(precision: 7, storeType: "datetime2"));
            AddColumn("dbo.Plugins", "Deleted", c => c.Boolean(nullable: false));
            AddColumn("dbo.Plugins", "IsActive", c => c.Boolean(nullable: false));
            AddColumn("dbo.Plugins", "Name", c => c.String());
            AlterColumn("dbo.UArtists", "ArchiveDate", c => c.DateTime(precision: 7, storeType: "datetime2"));
            AlterColumn("dbo.UArtists", "ModifiedDate", c => c.DateTime(precision: 7, storeType: "datetime2"));
            AlterColumn("dbo.UArtists", "Created", c => c.DateTime(precision: 7, storeType: "datetime2"));
            AlterColumn("dbo.UArtists", "Modified", c => c.DateTime(precision: 7, storeType: "datetime2"));
            AlterColumn("dbo.UArtists", "CreatedDate", c => c.DateTime(precision: 7, storeType: "datetime2"));
            AlterColumn("dbo.UArtists", "DeleteDate", c => c.DateTime(precision: 7, storeType: "datetime2"));
            AlterColumn("dbo.MediaDirectories", "ArchiveDate", c => c.DateTime(precision: 7, storeType: "datetime2"));
            AlterColumn("dbo.MediaDirectories", "Created", c => c.DateTime(precision: 7, storeType: "datetime2"));
            AlterColumn("dbo.MediaDirectories", "Modified", c => c.DateTime(precision: 7, storeType: "datetime2"));
            AlterColumn("dbo.Media", "Created", c => c.DateTime(precision: 7, storeType: "datetime2"));
            AlterColumn("dbo.Media", "Modified", c => c.DateTime(precision: 7, storeType: "datetime2"));
            AlterColumn("dbo.Media", "ArchiveDate", c => c.DateTime(precision: 7, storeType: "datetime2"));
            AlterColumn("dbo.Media", "ModifiedDate", c => c.DateTime(precision: 7, storeType: "datetime2"));
            AlterColumn("dbo.Media", "CreatedDate", c => c.DateTime(precision: 7, storeType: "datetime2"));
            AlterColumn("dbo.Media", "DeleteDate", c => c.DateTime(precision: 7, storeType: "datetime2"));
            AlterColumn("dbo.ApplicationUsers", "DeletedDate", c => c.DateTime(precision: 7, storeType: "datetime2"));
            AlterColumn("dbo.ApplicationUsers", "ModifiedDate", c => c.DateTime(precision: 7, storeType: "datetime2"));
            AlterColumn("dbo.ApplicationUsers", "Created", c => c.DateTime(precision: 7, storeType: "datetime2"));
            AlterColumn("dbo.ApplicationUsers", "Modified", c => c.DateTime(precision: 7, storeType: "datetime2"));
            AlterColumn("dbo.ApplicationUsers", "ArchiveDate", c => c.DateTime(precision: 7, storeType: "datetime2"));
            AlterColumn("dbo.ApplicationUsers", "CreatedDate", c => c.DateTime(precision: 7, storeType: "datetime2"));
            AlterColumn("dbo.ApplicationUsers", "DeleteDate", c => c.DateTime(precision: 7, storeType: "datetime2"));
            AlterColumn("dbo.UCountries", "ArchiveDate", c => c.DateTime(precision: 7, storeType: "datetime2"));
            AlterColumn("dbo.UCountries", "ModifiedDate", c => c.DateTime(precision: 7, storeType: "datetime2"));
            AlterColumn("dbo.UCountries", "Created", c => c.DateTime(precision: 7, storeType: "datetime2"));
            AlterColumn("dbo.UCountries", "Modified", c => c.DateTime(precision: 7, storeType: "datetime2"));
            AlterColumn("dbo.UCountries", "CreatedDate", c => c.DateTime(precision: 7, storeType: "datetime2"));
            AlterColumn("dbo.UCountries", "DeleteDate", c => c.DateTime(precision: 7, storeType: "datetime2"));
            AlterColumn("dbo.UGenres", "ModifiedDate", c => c.DateTime(precision: 7, storeType: "datetime2"));
            AlterColumn("dbo.UGenres", "Created", c => c.DateTime(precision: 7, storeType: "datetime2"));
            AlterColumn("dbo.UGenres", "Modified", c => c.DateTime(precision: 7, storeType: "datetime2"));
            AlterColumn("dbo.UGenres", "ArchiveDate", c => c.DateTime(precision: 7, storeType: "datetime2"));
            AlterColumn("dbo.UGenres", "CreatedDate", c => c.DateTime(precision: 7, storeType: "datetime2"));
            AlterColumn("dbo.UGenres", "DeleteDate", c => c.DateTime(precision: 7, storeType: "datetime2"));
            AlterColumn("dbo.SocialProfileTypes", "Created", c => c.DateTime(precision: 7, storeType: "datetime2"));
            AlterColumn("dbo.SocialProfileTypes", "Modified", c => c.DateTime(precision: 7, storeType: "datetime2"));
            AlterColumn("dbo.UFestivals", "ArchiveDate", c => c.DateTime(precision: 7, storeType: "datetime2"));
            AlterColumn("dbo.UFestivals", "ModifiedDate", c => c.DateTime(precision: 7, storeType: "datetime2"));
            AlterColumn("dbo.UFestivals", "Created", c => c.DateTime(precision: 7, storeType: "datetime2"));
            AlterColumn("dbo.UFestivals", "Modified", c => c.DateTime(precision: 7, storeType: "datetime2"));
            AlterColumn("dbo.UFestivals", "CreatedDate", c => c.DateTime(precision: 7, storeType: "datetime2"));
            AlterColumn("dbo.UFestivals", "DeleteDate", c => c.DateTime(precision: 7, storeType: "datetime2"));
            AlterColumn("dbo.Locations", "Created", c => c.DateTime(precision: 7, storeType: "datetime2"));
            AlterColumn("dbo.Locations", "Modified", c => c.DateTime(precision: 7, storeType: "datetime2"));
            AlterColumn("dbo.Locations", "ArchiveDate", c => c.DateTime(precision: 7, storeType: "datetime2"));
            AlterColumn("dbo.Locations", "ModifiedDate", c => c.DateTime(precision: 7, storeType: "datetime2"));
            AlterColumn("dbo.Locations", "CreatedDate", c => c.DateTime(precision: 7, storeType: "datetime2"));
            AlterColumn("dbo.Locations", "DeleteDate", c => c.DateTime(precision: 7, storeType: "datetime2"));
            AlterColumn("dbo.Stages", "ModifiedDate", c => c.DateTime(precision: 7, storeType: "datetime2"));
            AlterColumn("dbo.Stages", "Created", c => c.DateTime(precision: 7, storeType: "datetime2"));
            AlterColumn("dbo.Stages", "Modified", c => c.DateTime(precision: 7, storeType: "datetime2"));
            AlterColumn("dbo.Stages", "ArchiveDate", c => c.DateTime(precision: 7, storeType: "datetime2"));
            AlterColumn("dbo.Stages", "CreatedDate", c => c.DateTime(precision: 7, storeType: "datetime2"));
            AlterColumn("dbo.Stages", "DeleteDate", c => c.DateTime(precision: 7, storeType: "datetime2"));
            AlterColumn("dbo.LineupItems", "StartDate", c => c.DateTime(nullable: false, precision: 7, storeType: "datetime2"));
            AlterColumn("dbo.LineupItems", "EndDate", c => c.DateTime(nullable: false, precision: 7, storeType: "datetime2"));
            AlterColumn("dbo.Tickets", "ArchiveDate", c => c.DateTime(precision: 7, storeType: "datetime2"));
            AlterColumn("dbo.Tickets", "ModifiedDate", c => c.DateTime(precision: 7, storeType: "datetime2"));
            AlterColumn("dbo.Tickets", "Created", c => c.DateTime(precision: 7, storeType: "datetime2"));
            AlterColumn("dbo.Tickets", "Modified", c => c.DateTime(precision: 7, storeType: "datetime2"));
            AlterColumn("dbo.Tickets", "CreatedDate", c => c.DateTime(precision: 7, storeType: "datetime2"));
            AlterColumn("dbo.Tickets", "DeleteDate", c => c.DateTime(precision: 7, storeType: "datetime2"));
            AlterColumn("dbo.Advertisements", "Expires", c => c.DateTime(precision: 7, storeType: "datetime2"));
            AlterColumn("dbo.Advertisements", "PublishDate", c => c.DateTime(precision: 7, storeType: "datetime2"));
            AlterColumn("dbo.Advertisements", "ModifiedDate", c => c.DateTime(precision: 7, storeType: "datetime2"));
            AlterColumn("dbo.Advertisements", "Created", c => c.DateTime(precision: 7, storeType: "datetime2"));
            AlterColumn("dbo.Advertisements", "Modified", c => c.DateTime(precision: 7, storeType: "datetime2"));
            AlterColumn("dbo.Advertisements", "ArchiveDate", c => c.DateTime(precision: 7, storeType: "datetime2"));
            AlterColumn("dbo.Advertisements", "CreatedDate", c => c.DateTime(precision: 7, storeType: "datetime2"));
            AlterColumn("dbo.Advertisements", "DeleteDate", c => c.DateTime(precision: 7, storeType: "datetime2"));
            AlterColumn("dbo.Resellers", "ModifiedDate", c => c.DateTime(precision: 7, storeType: "datetime2"));
            AlterColumn("dbo.Resellers", "Created", c => c.DateTime(precision: 7, storeType: "datetime2"));
            AlterColumn("dbo.Resellers", "Modified", c => c.DateTime(precision: 7, storeType: "datetime2"));
            AlterColumn("dbo.Resellers", "ArchiveDate", c => c.DateTime(precision: 7, storeType: "datetime2"));
            AlterColumn("dbo.Resellers", "CreatedDate", c => c.DateTime(precision: 7, storeType: "datetime2"));
            AlterColumn("dbo.Resellers", "DeleteDate", c => c.DateTime(precision: 7, storeType: "datetime2"));
            AlterColumn("dbo.ResellerTypes", "Created", c => c.DateTime(precision: 7, storeType: "datetime2"));
            AlterColumn("dbo.ResellerTypes", "Modified", c => c.DateTime(precision: 7, storeType: "datetime2"));
            AlterColumn("dbo.ResellerTypes", "ArchiveDate", c => c.DateTime(precision: 7, storeType: "datetime2"));
            AlterColumn("dbo.ResellerGenres", "Created", c => c.DateTime(precision: 7, storeType: "datetime2"));
            AlterColumn("dbo.ResellerGenres", "Modified", c => c.DateTime(precision: 7, storeType: "datetime2"));
            AlterColumn("dbo.ResellerGenres", "ArchiveDate", c => c.DateTime(precision: 7, storeType: "datetime2"));
            AlterColumn("dbo.AppUserSessions", "Expires", c => c.DateTime(nullable: false, precision: 7, storeType: "datetime2"));
            AlterColumn("dbo.AppUserSessions", "Created", c => c.DateTime(nullable: false, precision: 7, storeType: "datetime2"));
            AlterColumn("dbo.AppUserSessions", "Modified", c => c.DateTime(nullable: false, precision: 7, storeType: "datetime2"));
            AlterColumn("dbo.CalendarCardAds", "Created", c => c.DateTime(precision: 7, storeType: "datetime2"));
            AlterColumn("dbo.CalendarCardAds", "Modified", c => c.DateTime(precision: 7, storeType: "datetime2"));
            AlterColumn("dbo.CalendarCardAds", "ArchiveDate", c => c.DateTime(precision: 7, storeType: "datetime2"));
            AlterColumn("dbo.UNews", "Date", c => c.DateTime(nullable: false, precision: 7, storeType: "datetime2"));
            AlterColumn("dbo.UNews", "CreateDate", c => c.DateTime(nullable: false, precision: 7, storeType: "datetime2"));
            AlterColumn("dbo.UNews", "ModifiedDate", c => c.DateTime(precision: 7, storeType: "datetime2"));
            AlterColumn("dbo.UNews", "Created", c => c.DateTime(precision: 7, storeType: "datetime2"));
            AlterColumn("dbo.UNews", "Modified", c => c.DateTime(precision: 7, storeType: "datetime2"));
            AlterColumn("dbo.UNews", "ArchiveDate", c => c.DateTime(precision: 7, storeType: "datetime2"));
            AlterColumn("dbo.UNews", "CreatedDate", c => c.DateTime(precision: 7, storeType: "datetime2"));
            AlterColumn("dbo.UNews", "DeleteDate", c => c.DateTime(precision: 7, storeType: "datetime2"));
            AlterColumn("dbo.GenericMessages", "Created", c => c.DateTime(nullable: false, precision: 7, storeType: "datetime2"));
            AlterColumn("dbo.GenericMessages", "ArchiveDate", c => c.DateTime(nullable: false, precision: 7, storeType: "datetime2"));
            AlterColumn("dbo.MenuItems", "ModifiedDate", c => c.DateTime(precision: 7, storeType: "datetime2"));
            AlterColumn("dbo.MenuItems", "Created", c => c.DateTime(precision: 7, storeType: "datetime2"));
            AlterColumn("dbo.MenuItems", "Modified", c => c.DateTime(precision: 7, storeType: "datetime2"));
            AlterColumn("dbo.MenuItems", "ArchiveDate", c => c.DateTime(precision: 7, storeType: "datetime2"));
            AlterColumn("dbo.MenuItems", "CreatedDate", c => c.DateTime(precision: 7, storeType: "datetime2"));
            AlterColumn("dbo.MenuItems", "DeleteDate", c => c.DateTime(precision: 7, storeType: "datetime2"));
            AlterColumn("dbo.MenuSections", "ModifiedDate", c => c.DateTime(precision: 7, storeType: "datetime2"));
            AlterColumn("dbo.MenuSections", "Created", c => c.DateTime(precision: 7, storeType: "datetime2"));
            AlterColumn("dbo.MenuSections", "Modified", c => c.DateTime(precision: 7, storeType: "datetime2"));
            AlterColumn("dbo.MenuSections", "ArchiveDate", c => c.DateTime(precision: 7, storeType: "datetime2"));
            AlterColumn("dbo.MenuSections", "CreatedDate", c => c.DateTime(precision: 7, storeType: "datetime2"));
            AlterColumn("dbo.MenuSections", "DeleteDate", c => c.DateTime(precision: 7, storeType: "datetime2"));
            AlterColumn("dbo.Plugins", "ArchiveDate", c => c.DateTime(precision: 7, storeType: "datetime2"));
            AlterColumn("dbo.Plugins", "Created", c => c.DateTime(precision: 7, storeType: "datetime2"));
            AlterColumn("dbo.Plugins", "Modified", c => c.DateTime(precision: 7, storeType: "datetime2"));
            AlterColumn("dbo.Plugins", "Expires", c => c.DateTime(nullable: false, precision: 7, storeType: "datetime2"));
            AlterColumn("dbo.Products", "ArchiveDate", c => c.DateTime(precision: 7, storeType: "datetime2"));
            AlterColumn("dbo.Products", "ModifiedDate", c => c.DateTime(precision: 7, storeType: "datetime2"));
            AlterColumn("dbo.Products", "Created", c => c.DateTime(precision: 7, storeType: "datetime2"));
            AlterColumn("dbo.Products", "Modified", c => c.DateTime(precision: 7, storeType: "datetime2"));
            AlterColumn("dbo.Products", "CreatedDate", c => c.DateTime(precision: 7, storeType: "datetime2"));
            AlterColumn("dbo.Products", "DeleteDate", c => c.DateTime(precision: 7, storeType: "datetime2"));
            AlterColumn("dbo.ProfileHeaderAds", "Date", c => c.DateTime(nullable: false, precision: 7, storeType: "datetime2"));
            CreateIndex("dbo.SocialProfileTypes", "MediaID");
            CreateIndex("dbo.Advertisements", "Expires");
            CreateIndex("dbo.Advertisements", "PublishDate");
        }
        
        public override void Down()
        {
            DropIndex("dbo.Advertisements", new[] { "PublishDate" });
            DropIndex("dbo.Advertisements", new[] { "Expires" });
            DropIndex("dbo.SocialProfileTypes", new[] { "MediaID" });
            AlterColumn("dbo.ProfileHeaderAds", "Date", c => c.DateTime(nullable: false));
            AlterColumn("dbo.Products", "DeleteDate", c => c.DateTime());
            AlterColumn("dbo.Products", "CreatedDate", c => c.DateTime());
            AlterColumn("dbo.Products", "Modified", c => c.DateTime());
            AlterColumn("dbo.Products", "Created", c => c.DateTime());
            AlterColumn("dbo.Products", "ModifiedDate", c => c.DateTime());
            AlterColumn("dbo.Products", "ArchiveDate", c => c.DateTime());
            AlterColumn("dbo.Plugins", "Expires", c => c.DateTime(nullable: false));
            AlterColumn("dbo.Plugins", "Modified", c => c.DateTime(nullable: false));
            AlterColumn("dbo.Plugins", "Created", c => c.DateTime(nullable: false));
            AlterColumn("dbo.Plugins", "ArchiveDate", c => c.DateTime(nullable: false));
            AlterColumn("dbo.MenuSections", "DeleteDate", c => c.DateTime());
            AlterColumn("dbo.MenuSections", "CreatedDate", c => c.DateTime());
            AlterColumn("dbo.MenuSections", "ArchiveDate", c => c.DateTime());
            AlterColumn("dbo.MenuSections", "Modified", c => c.DateTime());
            AlterColumn("dbo.MenuSections", "Created", c => c.DateTime());
            AlterColumn("dbo.MenuSections", "ModifiedDate", c => c.DateTime());
            AlterColumn("dbo.MenuItems", "DeleteDate", c => c.DateTime());
            AlterColumn("dbo.MenuItems", "CreatedDate", c => c.DateTime());
            AlterColumn("dbo.MenuItems", "ArchiveDate", c => c.DateTime());
            AlterColumn("dbo.MenuItems", "Modified", c => c.DateTime());
            AlterColumn("dbo.MenuItems", "Created", c => c.DateTime());
            AlterColumn("dbo.MenuItems", "ModifiedDate", c => c.DateTime());
            AlterColumn("dbo.GenericMessages", "ArchiveDate", c => c.DateTime(nullable: false));
            AlterColumn("dbo.GenericMessages", "Created", c => c.DateTime(nullable: false));
            AlterColumn("dbo.UNews", "DeleteDate", c => c.DateTime());
            AlterColumn("dbo.UNews", "CreatedDate", c => c.DateTime());
            AlterColumn("dbo.UNews", "ArchiveDate", c => c.DateTime());
            AlterColumn("dbo.UNews", "Modified", c => c.DateTime());
            AlterColumn("dbo.UNews", "Created", c => c.DateTime());
            AlterColumn("dbo.UNews", "ModifiedDate", c => c.DateTime());
            AlterColumn("dbo.UNews", "CreateDate", c => c.DateTime(nullable: false));
            AlterColumn("dbo.UNews", "Date", c => c.DateTime(nullable: false));
            AlterColumn("dbo.CalendarCardAds", "ArchiveDate", c => c.DateTime());
            AlterColumn("dbo.CalendarCardAds", "Modified", c => c.DateTime());
            AlterColumn("dbo.CalendarCardAds", "Created", c => c.DateTime());
            AlterColumn("dbo.AppUserSessions", "Modified", c => c.DateTime(nullable: false));
            AlterColumn("dbo.AppUserSessions", "Created", c => c.DateTime(nullable: false));
            AlterColumn("dbo.AppUserSessions", "Expires", c => c.DateTime(nullable: false));
            AlterColumn("dbo.ResellerGenres", "ArchiveDate", c => c.DateTime());
            AlterColumn("dbo.ResellerGenres", "Modified", c => c.DateTime());
            AlterColumn("dbo.ResellerGenres", "Created", c => c.DateTime());
            AlterColumn("dbo.ResellerTypes", "ArchiveDate", c => c.DateTime());
            AlterColumn("dbo.ResellerTypes", "Modified", c => c.DateTime());
            AlterColumn("dbo.ResellerTypes", "Created", c => c.DateTime());
            AlterColumn("dbo.Resellers", "DeleteDate", c => c.DateTime());
            AlterColumn("dbo.Resellers", "CreatedDate", c => c.DateTime());
            AlterColumn("dbo.Resellers", "ArchiveDate", c => c.DateTime());
            AlterColumn("dbo.Resellers", "Modified", c => c.DateTime());
            AlterColumn("dbo.Resellers", "Created", c => c.DateTime());
            AlterColumn("dbo.Resellers", "ModifiedDate", c => c.DateTime());
            AlterColumn("dbo.Advertisements", "DeleteDate", c => c.DateTime());
            AlterColumn("dbo.Advertisements", "CreatedDate", c => c.DateTime());
            AlterColumn("dbo.Advertisements", "ArchiveDate", c => c.DateTime());
            AlterColumn("dbo.Advertisements", "Modified", c => c.DateTime());
            AlterColumn("dbo.Advertisements", "Created", c => c.DateTime());
            AlterColumn("dbo.Advertisements", "ModifiedDate", c => c.DateTime());
            AlterColumn("dbo.Advertisements", "PublishDate", c => c.DateTime());
            AlterColumn("dbo.Advertisements", "Expires", c => c.DateTime());
            AlterColumn("dbo.Tickets", "DeleteDate", c => c.DateTime());
            AlterColumn("dbo.Tickets", "CreatedDate", c => c.DateTime());
            AlterColumn("dbo.Tickets", "Modified", c => c.DateTime());
            AlterColumn("dbo.Tickets", "Created", c => c.DateTime());
            AlterColumn("dbo.Tickets", "ModifiedDate", c => c.DateTime());
            AlterColumn("dbo.Tickets", "ArchiveDate", c => c.DateTime());
            AlterColumn("dbo.LineupItems", "EndDate", c => c.DateTime(nullable: false));
            AlterColumn("dbo.LineupItems", "StartDate", c => c.DateTime(nullable: false));
            AlterColumn("dbo.Stages", "DeleteDate", c => c.DateTime());
            AlterColumn("dbo.Stages", "CreatedDate", c => c.DateTime());
            AlterColumn("dbo.Stages", "ArchiveDate", c => c.DateTime());
            AlterColumn("dbo.Stages", "Modified", c => c.DateTime());
            AlterColumn("dbo.Stages", "Created", c => c.DateTime());
            AlterColumn("dbo.Stages", "ModifiedDate", c => c.DateTime());
            AlterColumn("dbo.Locations", "DeleteDate", c => c.DateTime());
            AlterColumn("dbo.Locations", "CreatedDate", c => c.DateTime());
            AlterColumn("dbo.Locations", "ModifiedDate", c => c.DateTime());
            AlterColumn("dbo.Locations", "ArchiveDate", c => c.DateTime());
            AlterColumn("dbo.Locations", "Modified", c => c.DateTime());
            AlterColumn("dbo.Locations", "Created", c => c.DateTime());
            AlterColumn("dbo.UFestivals", "DeleteDate", c => c.DateTime());
            AlterColumn("dbo.UFestivals", "CreatedDate", c => c.DateTime());
            AlterColumn("dbo.UFestivals", "Modified", c => c.DateTime());
            AlterColumn("dbo.UFestivals", "Created", c => c.DateTime());
            AlterColumn("dbo.UFestivals", "ModifiedDate", c => c.DateTime());
            AlterColumn("dbo.UFestivals", "ArchiveDate", c => c.DateTime());
            AlterColumn("dbo.SocialProfileTypes", "Modified", c => c.DateTime(nullable: false));
            AlterColumn("dbo.SocialProfileTypes", "Created", c => c.DateTime(nullable: false));
            AlterColumn("dbo.UGenres", "DeleteDate", c => c.DateTime());
            AlterColumn("dbo.UGenres", "CreatedDate", c => c.DateTime());
            AlterColumn("dbo.UGenres", "ArchiveDate", c => c.DateTime());
            AlterColumn("dbo.UGenres", "Modified", c => c.DateTime());
            AlterColumn("dbo.UGenres", "Created", c => c.DateTime());
            AlterColumn("dbo.UGenres", "ModifiedDate", c => c.DateTime());
            AlterColumn("dbo.UCountries", "DeleteDate", c => c.DateTime());
            AlterColumn("dbo.UCountries", "CreatedDate", c => c.DateTime());
            AlterColumn("dbo.UCountries", "Modified", c => c.DateTime());
            AlterColumn("dbo.UCountries", "Created", c => c.DateTime());
            AlterColumn("dbo.UCountries", "ModifiedDate", c => c.DateTime());
            AlterColumn("dbo.UCountries", "ArchiveDate", c => c.DateTime());
            AlterColumn("dbo.ApplicationUsers", "DeleteDate", c => c.DateTime());
            AlterColumn("dbo.ApplicationUsers", "CreatedDate", c => c.DateTime());
            AlterColumn("dbo.ApplicationUsers", "ArchiveDate", c => c.DateTime());
            AlterColumn("dbo.ApplicationUsers", "Modified", c => c.DateTime());
            AlterColumn("dbo.ApplicationUsers", "Created", c => c.DateTime());
            AlterColumn("dbo.ApplicationUsers", "ModifiedDate", c => c.DateTime());
            AlterColumn("dbo.ApplicationUsers", "DeletedDate", c => c.DateTime());
            AlterColumn("dbo.Media", "DeleteDate", c => c.DateTime());
            AlterColumn("dbo.Media", "CreatedDate", c => c.DateTime());
            AlterColumn("dbo.Media", "ModifiedDate", c => c.DateTime());
            AlterColumn("dbo.Media", "ArchiveDate", c => c.DateTime());
            AlterColumn("dbo.Media", "Modified", c => c.DateTime());
            AlterColumn("dbo.Media", "Created", c => c.DateTime());
            AlterColumn("dbo.MediaDirectories", "Modified", c => c.DateTime());
            AlterColumn("dbo.MediaDirectories", "Created", c => c.DateTime());
            AlterColumn("dbo.MediaDirectories", "ArchiveDate", c => c.DateTime());
            AlterColumn("dbo.UArtists", "DeleteDate", c => c.DateTime());
            AlterColumn("dbo.UArtists", "CreatedDate", c => c.DateTime());
            AlterColumn("dbo.UArtists", "Modified", c => c.DateTime());
            AlterColumn("dbo.UArtists", "Created", c => c.DateTime());
            AlterColumn("dbo.UArtists", "ModifiedDate", c => c.DateTime());
            AlterColumn("dbo.UArtists", "ArchiveDate", c => c.DateTime());
            DropColumn("dbo.Plugins", "Name");
            DropColumn("dbo.Plugins", "IsActive");
            DropColumn("dbo.Plugins", "Deleted");
            DropColumn("dbo.Plugins", "DeleteDate");
            DropColumn("dbo.Plugins", "CreatedDate");
            DropColumn("dbo.Plugins", "URL");
            DropColumn("dbo.Plugins", "SortOrder");
            DropColumn("dbo.Plugins", "IsPublished");
            DropColumn("dbo.Plugins", "ModifiedDate");
            DropColumn("dbo.UNews", "Name");
            DropColumn("dbo.CalendarCardAds", "Name");
            DropColumn("dbo.CalendarCardAds", "IsActive");
            DropColumn("dbo.CalendarCardAds", "Deleted");
            DropColumn("dbo.CalendarCardAds", "DeleteDate");
            DropColumn("dbo.CalendarCardAds", "CreatedDate");
            DropColumn("dbo.CalendarCardAds", "URL");
            DropColumn("dbo.CalendarCardAds", "SortOrder");
            DropColumn("dbo.CalendarCardAds", "IsPublished");
            DropColumn("dbo.CalendarCardAds", "ModifiedDate");
            DropColumn("dbo.ResellerGenres", "Name");
            DropColumn("dbo.ResellerGenres", "IsActive");
            DropColumn("dbo.ResellerGenres", "Deleted");
            DropColumn("dbo.ResellerGenres", "DeleteDate");
            DropColumn("dbo.ResellerGenres", "CreatedDate");
            DropColumn("dbo.ResellerGenres", "URL");
            DropColumn("dbo.ResellerGenres", "SortOrder");
            DropColumn("dbo.ResellerGenres", "IsPublished");
            DropColumn("dbo.ResellerGenres", "ModifiedDate");
            DropColumn("dbo.ResellerTypes", "IsActive");
            DropColumn("dbo.ResellerTypes", "Deleted");
            DropColumn("dbo.ResellerTypes", "DeleteDate");
            DropColumn("dbo.ResellerTypes", "CreatedDate");
            DropColumn("dbo.ResellerTypes", "URL");
            DropColumn("dbo.ResellerTypes", "SortOrder");
            DropColumn("dbo.ResellerTypes", "IsPublished");
            DropColumn("dbo.ResellerTypes", "ModifiedDate");
            DropColumn("dbo.SocialProfileTypes", "IsActive");
            DropColumn("dbo.SocialProfileTypes", "IsDeleted");
            DropColumn("dbo.SocialProfileTypes", "Deleted");
            DropColumn("dbo.SocialProfileTypes", "AuthorID");
            DropColumn("dbo.SocialProfileTypes", "DeleteDate");
            DropColumn("dbo.SocialProfileTypes", "CreatedDate");
            DropColumn("dbo.SocialProfileTypes", "ArchiveDate");
            DropColumn("dbo.SocialProfileTypes", "URL");
            DropColumn("dbo.SocialProfileTypes", "SortOrder");
            DropColumn("dbo.SocialProfileTypes", "IsPublished");
            DropColumn("dbo.SocialProfileTypes", "ModifiedDate");
            CreateIndex("dbo.Advertisements", "PublishDate");
            CreateIndex("dbo.Advertisements", "Expires");
        }
    }
}
